Fix unification case between inj and function
runtimeverification/hs-backend-booster pull request #544
Opened 2024-03-08 10:05 UTC by goodlyrottenapple

2024-03-08 14:49 UTC, goodlyrottenapple commented
# KEVM

| Test                                                                  | sam-unifier-inj-fix time | master-cd8bac1 time | (sam-unifier-inj-fix/master-cd8bac1) time
|-----------------------------------------------------------------------|--------------------------|---------------------|-------------------------------------------
| kontrol/test-arithmetictest-test_max1_broken-uint256-uint256-0-spec.k | 53.84                    | 55.79               | 0.9650474995518911
| mcd/vat-move-diff-rough-spec.k                                        | 180.83                   | 171.4               | 1.055017502917153
| TOTAL                                                                 | 234.67000000000002       | 227.19              | 1.0329239843302964

2024-03-12 12:15 UTC, jberthold approved these changes

2024-03-12 15:32 UTC, ehildenb requested changes
We _must_ have a test for this! The fact that there was a regression is the best indicator that it could happen again!

2024-03-13 16:39 UTC, ehildenb approved these changes

2024-03-14 11:23 UTC, merged